version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_test_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql_db
        target: /var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 13306:3306
  go:
    container_name: gin_test
    build:
      context: .
      dockerfile: go/Dockerfile
      args:
        DB_USER: ${MYSQL_USER}
        DB_PASS: ${MYSQL_PASSWORD}
        HOST_NAME: "mysql_test_db"
        DB_PORT: "13306"
        DB_NAME: ${MYSQL_DATABASE}
    tty: true
    ports:
      - 8088:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /go/src
    tty: true
volumes:
 mysql_db:

